# Generated by Django 5.1.7 on 2025-03-24 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_wishlist_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Wishlist',
        ),
    ]
