# Generated by Django 5.1.7 on 2025-03-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
